// models/UserDailyCuration.js
import { DataTypes } from "sequelize";
import { sequelize } from "../config/db.js";

// 🗓️ UserDailyCuration — one item placed into a specific user's daily curation.
// An admin (and later the Vizzy AI) fills these in; the user reads them in the app.
// itemType:
//   "artwork"    -> DeckovizCuration.id (a curated artwork)
//   "collection" -> Collection.id
export const UserDailyCuration = sequelize.define(
  "UserDailyCuration",
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    userId: {
      type: DataTypes.UUID,
      allowNull: false, // recipient of the curation
    },
    itemType: {
      type: DataTypes.STRING, // "artwork" | "collection"
      allowNull: false,
    },
    itemId: {
      type: DataTypes.UUID,
      allowNull: false,
    },
    displayDate: {
      type: DataTypes.DATEONLY, // which day this item belongs to (e.g. 2026-05-31)
      allowNull: false,
    },
    order: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
    },
    seenAt: {
      type: DataTypes.DATE,
      allowNull: true, // set when the user first opens this item
    },
    addedBy: {
      type: DataTypes.UUID,
      allowNull: true, // admin user id, or null when generated by Vizzy
    },
  },
  {
    tableName: "user_daily_curations",
    timestamps: true,
    indexes: [
      { fields: ["userId", "displayDate"] },
      {
        unique: true,
        fields: ["userId", "displayDate", "itemType", "itemId"],
      },
    ],
  }
);

export const DAILY_CURATION_ITEM_TYPES = ["artwork", "collection"];
